// AquaEquity System Constants & Enums

export const ROLES = {
  CITIZEN: 'CITIZEN',
  ADMIN: 'ADMIN',
  AUTHORITY: 'AUTHORITY',
};

export const REQUEST_STATUS = {
  REQUESTED: 'REQUESTED',
  PRIORITY_CALCULATED: 'PRIORITY_CALCULATED',
  ASSIGNED: 'ASSIGNED',
  IN_TRANSIT: 'IN_TRANSIT',
  ARRIVED: 'ARRIVED',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  VERIFIED: 'VERIFIED',
  COMPLETED: 'COMPLETED',
  DISPLACED: 'DISPLACED',
  REASSIGNED: 'REASSIGNED',
  CANCELLED: 'CANCELLED',
};

export const PRIORITY_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

export const FACILITY_TYPES = {
  HOUSEHOLD: 'HOUSEHOLD',
  SLUM_COMMUNITY: 'SLUM_COMMUNITY',
  HOSPITAL_CLINIC: 'HOSPITAL_CLINIC',
  SCHOOL_HOSTEL: 'SCHOOL_HOSTEL',
  RELIEF_CAMP: 'RELIEF_CAMP',
  COMMUNITY_WELL: 'COMMUNITY_WELL',
  COMMERCIAL: 'COMMERCIAL',
};

export const TANKER_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ASSIGNED: 'ASSIGNED',
  IN_TRANSIT: 'IN_TRANSIT',
  DISPENSING: 'DISPENSING',
  MAINTENANCE: 'MAINTENANCE',
  OFFLINE: 'OFFLINE',
};

export const GEOFENCE_STATUS = {
  INSIDE: 'INSIDE',
  APPROACHING: 'APPROACHING',
  OUTSIDE: 'OUTSIDE',
};
